# Final Project Submission

Please fill out:
* Student name: Kristen Davis
* Student pace: Full Time
* Scheduled project review date/time: 11/16 @ 11:30
* Instructor name: Rafael Carrasco
* Blog post URL:

In [ ]:
https://rstudio-pubs-static.s3.amazonaws.com/339668_006f4906390e41cea23b3b786cc0230a.html

## Set Up & Data Initialization

In [238]:
#Libraries 
import pandas as pd    

import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px 
import plotly.graph_objects as go 
from plotly.subplots import make_subplots  
%matplotlib inline


import plotly.io as pio
pio.renderers.default='notebook'

In [239]:
#Functions
def explore_df(df): 
    """Input: Takes in a DataFrame 
    Returns: shape, column names, non-null count, dtype, general statistical description, column values counts"""
    print(df.shape)
    print(df.isna().sum())
    print(list(df.columns)) 
    print(df.info()) 
    print(df.describe()) 
    return[df[col].value_counts() for col in df.columns]

### Load Data Sets

In [240]:
#Data for this contest downloaded from datadriven.org
test_set_values = pd.read_csv('/Users/kristen/Downloads/702ddfc5-68cd-4d1d-a0de-f5f566f76d91.csv') 
training_set_labels = pd.read_csv('/Users/kristen/Downloads/0bf8bc6e-30d0-4c50-956a-603fc693d966.csv')   
training_set_values = pd.read_csv('/Users/kristen/Downloads/4910797b-ee55-40a7-8668-10efd5c1b960.csv')

In [241]:
#Merge training set
df = pd.merge(training_set_labels, training_set_values, on="id")

In [242]:
#Explore Data  
explore_df(df=df)

(59400, 41)
id                           0
status_group                 0
amount_tsh                   0
date_recorded                0
funder                    3635
gps_height                   0
installer                 3655
longitude                    0
latitude                     0
wpt_name                     0
num_private                  0
basin                        0
subvillage                 371
region                       0
region_code                  0
district_code                0
lga                          0
ward                         0
population                   0
public_meeting            3334
recorded_by                  0
scheme_management         3877
scheme_name              28166
permit                    3056
construction_year            0
extraction_type              0
extraction_type_group        0
extraction_type_class        0
management                   0
management_group             0
payment                      0
payment_type                 0
water_quality                0
quality_group                0
quantity                     0
quantity_group               0
source                       0
source_type                  0
source_class                 0
waterpoint_type              0
waterpoint_type_group        0
dtype: int64
['id', 'status_group', 'amount_tsh', 'date_recorded', 'funder', 'gps_height', 'installer', 'longitude', 'latitude', 'wpt_name', 'num_private', 'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga', 'ward', 'population', 'public_meeting', 'recorded_by', 'scheme_management', 'scheme_name', 'permit', 'construction_year', 'extraction_type', 'extraction_type_group', 'extraction_type_class', 'management', 'management_group', 'payment', 'payment_type', 'water_quality', 'quality_group', 'quantity', 'quantity_group', 'source', 'source_type', 'source_class', 'waterpoint_type', 'waterpoint_type_group']
<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 0 to 59399
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   status_group           59400 non-null  object
 2   amount_tsh             59400 non-null  float64
 3   date_recorded          59400 non-null  object
 4   funder                 55765 non-null  object
 5   gps_height             59400 non-null  int64
 6   installer              55745 non-null  object
 7   longitude              59400 non-null  float64
 8   latitude               59400 non-null  float64
 9   wpt_name               59400 non-null  object
 10  num_private            59400 non-null  int64
 11  basin                  59400 non-null  object
 12  subvillage             59029 non-null  object
 13  region                 59400 non-null  object
 14  region_code            59400 non-null  int64
 15  district_code          59400 non-null  int64
 16  lga                    59400 non-null  object
 17  ward                   59400 non-null  object
 18  population             59400 non-null  int64
 19  public_meeting         56066 non-null  object
 20  recorded_by            59400 non-null  object
 21  scheme_management      55523 non-null  object
 22  scheme_name            31234 non-null  object
 23  permit                 56344 non-null  object
 24  construction_year      59400 non-null  int64
 25  extraction_type        59400 non-null  object
 26  extraction_type_group  59400 non-null  object
 27  extraction_type_class  59400 non-null  object
 28  management             59400 non-null  object
 29  management_group       59400 non-null  object
 30  payment                59400 non-null  object
 31  payment_type           59400 non-null  object
 32  water_quality          59400 non-null  object
 33  quality_group          59400 non-null  object
 34  quantity               59400 non-null  object
 35  quantity_group         59400 non-null  object
 36  source                 59400 non-null  object
 37  source_type            59400 non-null  object
 38  source_class           59400 non-null  object
 39  waterpoint_type        59400 non-null  object
 40  waterpoint_type_group  59400 non-null  object
dtypes: float64(3), int64(7), object(31)
memory usage: 19.0+ MB
None
                 id     amount_tsh    gps_height     longitude      latitude  \
count  59400.000000   59400.000000  59400.000000  59400.000000  5.940000e+04
mean   37115.131768     317.650385    668.297239     34.077427 -5.706033e+00
std    21453.128371    2997.574558    693.116350      6.567432  2.946019e+00
min        0.000000       0.000000    -90.000000      0.000000 -1.164944e+01
25%    18519.750000       0.000000      0.000000     33.090347 -8.540621e+00
50%    37061.500000       0.000000    369.000000     34.908743 -5.021597e+00
75%    55656.500000      20.000000   1319.250000     37.178387 -3.326156e+00
max    74247.000000  350000.000000   2770.000000     40.345193 -2.000000e-08

        num_private   region_code  district_code    population  \
count  59400.000000  59400.000000   59400.000000  59400.000000
mean       0.474141     15.297003       5.629747    179.909983
std       12.236230     17.587406       9.633649    471.482176
min        0.000000      1.000000       0.000000      0.000000
25%        0.000000      5.000000       2.000000      0.000000
50%        0.000000     12.000000       3.000000     25.000000
75%        0.000000     17.000000       5.000000    215.000000
max     1776.000000     99.000000      80.000000  30500.000000

       construction_year
count       59400.000000
mean         1300.652475
std           951.620547
min             0.000000
25%             0.000000
50%          1986.000000
75%          2004.000000
max          2013.000000

[2047     1
 72310    1
 49805    1
 51852    1
 62091    1
         ..
 46396    1
 36155    1
 34106    1
 38200    1
 0        1
 Name: id, Length: 59400, dtype: int64,
 functional                 32259
 non functional             22824
 functional needs repair     4317
 Name: status_group, dtype: int64,
 0.0         41639
 500.0        3102
 50.0         2472
 1000.0       1488
 20.0         1463
             ...
 8500.0          1
 6300.0          1
 220.0           1
 138000.0        1
 12.0            1
 Name: amount_tsh, Length: 98, dtype: int64,
 2011-03-15    572
 2011-03-17    558
 2013-02-03    546
 2011-03-14    520
 2011-03-16    513
              ...
 2011-09-17      1
 2011-09-15      1
 2011-09-25      1
 2002-10-14      1
 2011-09-13      1
 Name: date_recorded, Length: 356, dtype: int64,
 Government Of Tanzania    9084
 Danida                    3114
 Hesawa                    2202
 Rwssp                     1374
 World Bank                1349
                           ...
 Jamal Abdallah               1
 Dgv                          1
 Unhcr/danida                 1
 Kanisani                     1
 Ccp                          1
 Name: funder, Length: 1897, dtype: int64,
  0       20438
 -15         60
 -16         55
 -13         55
 -20         52
          ...
  2285        1
  2424        1
  2552        1
  2413        1
  2385        1
 Name: gps_height, Length: 2428, dtype: int64,
 DWE                17402
 Government          1825
 RWE                 1206
 Commu               1060
 DANIDA              1050
                    ...
 mwakifuna              1
 Kidika                 1
 KOBERG                 1
 Mwamvita Rajabu        1
 Biore                  1
 Name: installer, Length: 2145, dtype: int64,
 0.000000     1812
 37.540901       2
 33.010510       2
 39.093484       2
 32.972719       2
              ...
 37.579803       1
 33.196490       1
 34.017119       1
 33.788326       1
 30.163579       1
 Name: longitude, Length: 57516, dtype: int64,
 -2.000000e-08    1812
 -6.985842e+00       2
 -3.797579e+00       2
 -6.981884e+00       2
 -7.104625e+00       2
                  ...
 -5.726001e+00       1
 -9.646831e+00       1
 -8.124530e+00       1
 -2.535985e+00       1
 -2.598965e+00       1
 Name: latitude, Length: 57517, dtype: int64,
 none                       3563
 Shuleni                    1748
 Zahanati                    830
 Msikitini                   535
 Kanisani                    323
                            ...
 Kwa Elias Salum Kingalu       1
 Kwa Mzee Nawanje              1
 Kwa Daud Uromy                1
 Kwa Mathias Shayo             1
 Kwa Aloyse                    1
 Name: wpt_name, Length: 37400, dtype: int64,
 0      58643
 6         81
 1         73
 5         46
 8         46
        ...
 180        1
 213        1
 23         1
 55         1
 94         1
 Name: num_private, Length: 65, dtype: int64,
 Lake Victoria              10248
 Pangani                     8940
 Rufiji                      7976
 Internal                    7785
 Lake Tanganyika             6432
 Wami / Ruvu                 5987
 Lake Nyasa                  5085
 Ruvuma / Southern Coast     4493
 Lake Rukwa                  2454
 Name: basin, dtype: int64,
 Madukani     508
 Shuleni      506
 Majengo      502
 Kati         373
 Mtakuja      262
             ...
 Mumaliza       1
 Kaatoma        1
 Ng'Hona        1
 Msaghaa A      1
 Dihimba        1
 Name: subvillage, Length: 19287, dtype: int64,
 Iringa           5294
 Shinyanga        4982
 Mbeya            4639
 Kilimanjaro      4379
 Morogoro         4006
 Arusha           3350
 Kagera           3316
 Mwanza           3102
 Kigoma           2816
 Ruvuma           2640
 Pwani            2635
 Tanga            2547
 Dodoma           2201
 Singida          2093
 Mara             1969
 Tabora           1959
 Rukwa            1808
 Mtwara           1730
 Manyara          1583
 Lindi            1546
 Dar es Salaam     805
 Name: region, dtype: int64,
 11    5300
 17    5011
 12    4639
 3     4379
 5     4040
 18    3324
 19    3047
 2     3024
 16    2816
 10    2640
 4     2513
 1     2201
 13    2093
 14    1979
 20    1969
 15    1808
 6     1609
 21    1583
 80    1238
 60    1025
 90     917
 7      805
 99     423
 9      390
 24     326
 8      300
 40       1
 Name: region_code, dtype: int64,
 1     12203
 2     11173
 3      9998
 4      8999
 5      4356
 6      4074
 7      3343
 8      1043
 30      995
 33      874
 53      745
 43      505
 13      391
 23      293
 63      195
 62      109
 60       63
 0        23
 80       12
 67        6
 Name: district_code, dtype: int64,
 Njombe          2503
 Arusha Rural    1252
 Moshi Rural     1251
 Bariadi         1177
 Rungwe          1106
                 ...
 Moshi Urban       79
 Kigoma Urban      71
 Arusha Urban      63
 Lindi Urban       21
 Nyamagana          1
 Name: lga, Length: 125, dtype: int64,
 Igosi        307
 Imalinyi     252
 Siha Kati    232
 Mdandu       231
 Nduruma      217
             ...
 Izia           1
 Korongoni      1
 Kirongo        1
 Sungwisi       1
 Mawenzi        1
 Name: ward, Length: 2092, dtype: int64,
 0       21381
 1        7025
 200      1940
 150      1892
 250      1681
         ...
 3241        1
 1960        1
 1685        1
 2248        1
 1439        1
 Name: population, Length: 1049, dtype: int64,
 True     51011
 False     5055
 Name: public_meeting, dtype: int64,
 GeoData Consultants Ltd    59400
 Name: recorded_by, dtype: int64,
 VWC                 36793
 WUG                  5206
 Water authority      3153
 WUA                  2883
 Water Board          2748
 Parastatal           1680
 Private operator     1063
 Company              1061
 Other                 766
 SWC                    97
 Trust                  72
 None                    1
 Name: scheme_management, dtype: int64,
 K                               682
 None                            644
 Borehole                        546
 Chalinze wate                   405
 M                               400
                                ...
 AIC                               1
 Kwa mboko water supply            1
 IKTM 2                            1
 Rain water harest                 1
 Ibukoni kimanga water supply      1
 Name: scheme_name, Length: 2696, dtype: int64,
 True     38852
 False    17492
 Name: permit, dtype: int64,
 0       20709
 2010     2645
 2008     2613
 2009     2533
 2000     2091
 2007     1587
 2006     1471
 2003     1286
 2011     1256
 2004     1123
 2012     1084
 2002     1075
 1978     1037
 1995     1014
 2005     1011
 1999      979
 1998      966
 1990      954
 1985      945
 1980      811
 1996      811
 1984      779
 1982      744
 1994      738
 1972      708
 1974      676
 1997      644
 1992      640
 1993      608
 2001      540
 1988      521
 1983      488
 1975      437
 1986      434
 1976      414
 1970      411
 1991      324
 1989      316
 1987      302
 1981      238
 1977      202
 1979      192
 1973      184
 2013      176
 1971      145
 1960      102
 1967       88
 1963       85
 1968       77
 1969       59
 1964       40
 1962       30
 1961       21
 1965       19
 1966       17
 Name: construction_year, dtype: int64,
 gravity                      26780
 nira/tanira                   8154
 other                         6430
 submersible                   4764
 swn 80                        3670
 mono                          2865
 india mark ii                 2400
 afridev                       1770
 ksb                           1415
 other - rope pump              451
 other - swn 81                 229
 windmill                       117
 india mark iii                  98
 cemo                            90
 other - play pump               85
 walimi                          48
 climax                          32
 other - mkulima/shinyanga        2
 Name: extraction_type, dtype: int64,
 gravity            26780
 nira/tanira         8154
 other               6430
 submersible         6179
 swn 80              3670
 mono                2865
 india mark ii       2400
 afridev             1770
 rope pump            451
 other handpump       364
 other motorpump      122
 wind-powered         117
 india mark iii        98
 Name: extraction_type_group, dtype: int64,
 gravity         26780
 handpump        16456
 other            6430
 submersible      6179
 motorpump        2987
 rope pump         451
 wind-powered      117
 Name: extraction_type_class, dtype: int64,
 vwc                 40507
 wug                  6515
 water board          2933
 wua                  2535
 private operator     1971
 parastatal           1768
 water authority       904
 other                 844
 company               685
 unknown               561
 other - school         99
 trust                  78
 Name: management, dtype: int64,
 user-group    52490
 commercial     3638
 parastatal     1768
 other           943
 unknown         561
 Name: management_group, dtype: int64,
 never pay                25348
 pay per bucket            8985
 pay monthly               8300
 unknown                   8157
 pay when scheme fails     3914
 pay annually              3642
 other                     1054
 Name: payment, dtype: int64,
 never pay     25348
 per bucket     8985
 monthly        8300
 unknown        8157
 on failure     3914
 annually       3642
 other          1054
 Name: payment_type, dtype: int64,
 soft                  50818
 salty                  4856
 unknown                1876
 milky                   804
 coloured                490
 salty abandoned         339
 fluoride                200
 fluoride abandoned       17
 Name: water_quality, dtype: int64,
 good        50818
 salty        5195
 unknown      1876
 milky         804
 colored       490
 fluoride      217
 Name: quality_group, dtype: int64,
 enough          33186
 insufficient    15129
 dry              6246
 seasonal         4050
 unknown           789
 Name: quantity, dtype: int64,
 enough          33186
 insufficient    15129
 dry              6246
 seasonal         4050
 unknown           789
 Name: quantity_group, dtype: int64,
 spring                  17021
 shallow well            16824
 machine dbh             11075
 river                    9612
 rainwater harvesting     2295
 hand dtw                  874
 lake                      765
 dam                       656
 other                     212
 unknown                    66
 Name: source, dtype: int64,
 spring                  17021
 shallow well            16824
 borehole                11949
 river/lake              10377
 rainwater harvesting     2295
 dam                       656
 other                     278
 Name: source_type, dtype: int64,
 groundwater    45794
 surface        13328
 unknown          278
 Name: source_class, dtype: int64,
 communal standpipe             28522
 hand pump                      17488
 other                           6380
 communal standpipe multiple     6103
 improved spring                  784
 cattle trough                    116
 dam                                7
 Name: waterpoint_type, dtype: int64,
 communal standpipe    34625
 hand pump             17488
 other                  6380
 improved spring         784
 cattle trough           116
 dam                       7
 Name: waterpoint_type_group, dtype: int64]

Structure:
* The data has 59,400 unique enteries with 41 features(columns)  

Nan Values: 
* 3,635 values are missing in the funder & installer category (6% of data missing) 
* 371 values are missing from the subvillage category (>1% of data missing) 
* 3,334 values are missing from the public meeting category (5% of data missing)  
* 3,877 values are missing from the scheme management category (6.5% of data missing)
* 28,166 values are missing from the scheme name category (47% of data missing) 
* 3,056 values are missing from the permit category (5% of data missing)

### Column Types

In [243]:
df.columns

Index(['id', 'status_group', 'amount_tsh', 'date_recorded', 'funder',
       'gps_height', 'installer', 'longitude', 'latitude', 'wpt_name',
       'num_private', 'basin', 'subvillage', 'region', 'region_code',
       'district_code', 'lga', 'ward', 'population', 'public_meeting',
       'recorded_by', 'scheme_management', 'scheme_name', 'permit',
       'construction_year', 'extraction_type', 'extraction_type_group',
       'extraction_type_class', 'management', 'management_group', 'payment',
       'payment_type', 'water_quality', 'quality_group', 'quantity',
       'quantity_group', 'source', 'source_type', 'source_class',
       'waterpoint_type', 'waterpoint_type_group'],
      dtype='object')

In [244]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 0 to 59399
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     59400 non-null  int64
 1   status_group           59400 non-null  object
 2   amount_tsh             59400 non-null  float64
 3   date_recorded          59400 non-null  object
 4   funder                 55765 non-null  object
 5   gps_height             59400 non-null  int64
 6   installer              55745 non-null  object
 7   longitude              59400 non-null  float64
 8   latitude               59400 non-null  float64
 9   wpt_name               59400 non-null  object
 10  num_private            59400 non-null  int64
 11  basin                  59400 non-null  object
 12  subvillage             59029 non-null  object
 13  region                 59400 non-null  object
 14  region_code            59400 non-null  int64
 15  district_code          59400 non-null  int64
 16  lga                    59400 non-null  object
 17  ward                   59400 non-null  object
 18  population             59400 non-null  int64
 19  public_meeting         56066 non-null  object
 20  recorded_by            59400 non-null  object
 21  scheme_management      55523 non-null  object
 22  scheme_name            31234 non-null  object
 23  permit                 56344 non-null  object
 24  construction_year      59400 non-null  int64
 25  extraction_type        59400 non-null  object
 26  extraction_type_group  59400 non-null  object
 27  extraction_type_class  59400 non-null  object
 28  management             59400 non-null  object
 29  management_group       59400 non-null  object
 30  payment                59400 non-null  object
 31  payment_type           59400 non-null  object
 32  water_quality          59400 non-null  object
 33  quality_group          59400 non-null  object
 34  quantity               59400 non-null  object
 35  quantity_group         59400 non-null  object
 36  source                 59400 non-null  object
 37  source_type            59400 non-null  object
 38  source_class           59400 non-null  object
 39  waterpoint_type        59400 non-null  object
 40  waterpoint_type_group  59400 non-null  object
dtypes: float64(3), int64(7), object(31)
memory usage: 19.0+ MB

In [245]:
#itrative cell to look a unique values to identify type 
df['permit'].unique()

array([False, True, nan], dtype=object)

* <b>Reference</b> - 'id', 'date_recorded', 'recorded_by'


* <b>Categorical</b> - 'status_group', 'funder', 'installer', 'wpt_name', 'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga', 'ward', 'public_meeting', 'scheme_management', 'scheme_name', 'permit', 'construction_year', 'extraction_type', 'extraction_type_group', 'extraction_type_class', 'management', 'management_group', 'payment', 'payment_type', 'water_quality', 'quality_group', 'quantity', 'quantity_group', 'source', 'source_type', 'source_class', 'waterpoint_type', 'waterpoint_type_group'


* <b>Continous</b> - 'amount_tsh', 'gps_height', 'longitude', 'latitude', 'num_private', 'population'

## Investigate Each Reference Column

### id

In [246]:
df['id']

0        69572
1         8776
2        34310
3        67743
4        19728
         ...
59395    60739
59396    27263
59397    37057
59398    31282
59399    26348
Name: id, Length: 59400, dtype: int64

59400 unique identifing ids correlated to a unique water pump.

### date_recorded

In [247]:
df[['date_recorded']] 
print(df[['date_recorded']].isna().sum()) 
df[['date_recorded']].info

date_recorded    0
dtype: int64

<bound method DataFrame.info of       date_recorded
0        2011-03-14
1        2013-03-06
2        2013-02-25
3        2013-01-28
4        2011-07-13
...             ...
59395    2013-05-03
59396    2011-05-07
59397    2011-04-11
59398    2011-03-08
59399    2011-03-23

[59400 rows x 1 columns]>

In [251]:
df['date_recorded'] = pd.to_datetime(df['date_recorded'])

In [252]:
dr_df = df.groupby('date_recorded').count().reset_index()  
dr_df

,date_recorded,id,status_group,amount_tsh,funder,gps_height,installer,longitude,latitude,wpt_name,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,2002-10-14,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,2004-01-07,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,2004-03-01,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
3,2004-03-06,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,2004-04-01,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,2013-11-02,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
352,2013-11-03,194,194,194,194,194,194,194,194,194,...,194,194,194,194,194,194,194,194,194,194
353,2013-12-01,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
354,2013-12-02,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
355,2013-12-03,240,240,240,239,240,240,240,240,240,...,240,240,240,240,240,240,240,240,240,240

In [253]:
fig = px.line(dr_df, x='date_recorded', y='id')
fig.show()

* Date data was recorded for each pump.  
* Non NaN values  
* The majority of the obeservations after 2010 with the largest number of data (572) recorded in March of 2011

### recorded_by

In [263]:
df[['recorded_by']] 
print(df[['recorded_by']].isna().sum()) 
df[['recorded_by']].info() 
print(df['recorded_by'].unique())

recorded_by    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 0 to 59399
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   recorded_by  59400 non-null  object
dtypes: object(1)
memory usage: 928.1+ KB
['GeoData Consultants Ltd']

* All values/ observations recorded by GeoData Consultants Ltd
* No NaN values

## Investigate Each Categorical Column

### status_group

In [269]:
df[['status_group']] 
print(df[['status_group']].isna().sum())
df[['status_group']].info() 
print(df['status_group'].unique())

status_group    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 0 to 59399
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   status_group  59400 non-null  object
dtypes: object(1)
memory usage: 928.1+ KB
['functional' 'non functional' 'functional needs repair']

In [270]:
#Length of each new dataset
print(len(functional))
print(len(non_functional))
print(len(functional_needs_repair))

32259
22824
4317

In [271]:
labels = ['Functional', 'Non Functional', 'Functional Needs Repair']
values = [32259, 22824, 4317]

fig = go.Figure(data=[go.Pie(labels=labels, values=values)]) 
fig.update_traces(textposition='inside', textinfo='percent+label', title='Water Pump Status')
fig.show()

* These are the categories that ultimately the model is attempting to sort into. Functional, non functional, and funtional needs repair 
* 54.3% Functional Pumps/ 38.4% Non Functional/ 7.27% Functional Needs Repair 

61.57% of the pumps in the data set are functional

### funder

In [273]:
df[['funder']] 
print(df[['funder']].isna().sum())
df[['funder']].info()

funder    3635
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Int64Index: 59400 entries, 0 to 59399
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   funder  55765 non-null  object
dtypes: object(1)
memory usage: 928.1+ KB
['Roman' 'Grumeti' 'Lottery Club' ... 'Dina' 'Brown' 'Samlo']

In [276]:
print(df[['funder']].isna().sum())

funder    3635
dtype: int64

In [275]:
df.groupby('funder').count()

,id,status_group,amount_tsh,date_recorded,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
funder,,,,,,,,,,,,,,,,,,,,,
0,777,777,777,777,777,777,777,777,777,777,...,777,777,777,777,777,777,777,777,777,777
A/co Germany,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Aar,33,33,33,33,33,32,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
Abas Ka,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Abasia,43,43,43,43,43,43,43,43,43,43,...,43,43,43,43,43,43,43,43,43,43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zao,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Zao Water Spring,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
Zao Water Spring X,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Zinduka,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Zingibali Secondary,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [284]:
df.loc[df['funder'] == '0']

,id,status_group,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
145,28669,functional,50.0,2013-03-21,0,12,0,39.185710,-6.892593,Chekanao,...,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
152,60983,non functional,0.0,2013-03-16,0,-15,0,39.527114,-6.988748,Msikitini,...,never pay,salty,salty,dry,dry,machine dbh,borehole,groundwater,other,other
393,39749,non functional,0.0,2013-03-18,0,28,0,39.159887,-6.902548,Kwa Chambuso,...,unknown,unknown,unknown,unknown,unknown,machine dbh,borehole,groundwater,other,other
417,15832,non functional,50.0,2013-03-22,0,30,0,39.178404,-6.938013,Ccm Kivule,...,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
428,50233,non functional,0.0,2013-03-12,0,30,0,39.178849,-6.973206,Ofisi Ya Kata,...,never pay,unknown,unknown,dry,dry,shallow well,shallow well,groundwater,other,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59237,2138,non functional,59.0,2013-03-19,0,81,0,39.119109,-6.898919,Kata,...,per bucket,salty abandoned,salty,insufficient,insufficient,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59243,3396,functional,50.0,2013-03-16,0,-20,0,39.524021,-6.984802,Kwa Mariwala,...,per bucket,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
59276,62818,functional,50.0,2013-03-21,0,18,0,39.183790,-6.897566,Kwa Mkunduge,...,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59351,55322,functional,50.0,2013-03-18,0,-19,0,39.534599,-7.088183,Kwa China,...,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe
59387,26640,functional,100.0,2013-03-12,0,25,0,39.176480,-6.957098,Kwa Maliba,...,per bucket,soft,good,enough,enough,machine dbh,borehole,groundwater,communal standpipe,communal standpipe

* 3635 values are missing funder 
* Many of these enteries appear to be duplicates ie "Zao Water Spring/ Zao Water Spring X/ Zao" for example 
* Rows that have a 0 listed as a funder also have a 0 listed as an installer

### installer

### wpt_name

### basin

### subvillage

### region

### region_code

### district_code

### lga

In [ ]:
'ward', 'public_meeting', 'scheme_management', 'scheme_name', 'permit', 'construction_year', 'extraction_type', 'extraction_type_group', 'extraction_type_class', 'management', 'management_group', 'payment', 'payment_type', 'water_quality', 'quality_group', 'quantity', 'quantity_group', 'source', 'source_type', 'source_class', 'waterpoint_type', 'waterpoint_type_group'

## Investigate Each Continous Column

### amount_tsh

### gps_height

### longitude

### latitude

### num_private

### population

### Column Values & Duplicates

In [175]:
#column names 
df.columns

Index(['id', 'status_group', 'amount_tsh', 'date_recorded', 'funder',
       'gps_height', 'installer', 'longitude', 'latitude', 'wpt_name',
       'num_private', 'basin', 'subvillage', 'region', 'region_code',
       'district_code', 'lga', 'ward', 'population', 'public_meeting',
       'recorded_by', 'scheme_management', 'scheme_name', 'permit',
       'construction_year', 'extraction_type', 'extraction_type_group',
       'extraction_type_class', 'management', 'management_group', 'payment',
       'payment_type', 'water_quality', 'quality_group', 'quantity',
       'quantity_group', 'source', 'source_type', 'source_class',
       'waterpoint_type', 'waterpoint_type_group'],
      dtype='object')

In [176]:
#Visually inspect extraction columns
df[['extraction_type_class', 'extraction_type', 'extraction_type_group']]

      extraction_type_class extraction_type extraction_type_group
0                   gravity         gravity               gravity
1                   gravity         gravity               gravity
2                   gravity         gravity               gravity
3               submersible     submersible           submersible
4                   gravity         gravity               gravity
...                     ...             ...                   ...
59395               gravity         gravity               gravity
59396               gravity         gravity               gravity
59397              handpump          swn 80                swn 80
59398              handpump     nira/tanira           nira/tanira
59399              handpump     nira/tanira           nira/tanira

[59400 rows x 3 columns]

In [177]:
#Visually inpsect payment columns
df[['payment_type', 'payment']]

      payment_type                payment
0         annually           pay annually
1        never pay              never pay
2       per bucket         pay per bucket
3        never pay              never pay
4        never pay              never pay
...            ...                    ...
59395   per bucket         pay per bucket
59396     annually           pay annually
59397      monthly            pay monthly
59398    never pay              never pay
59399   on failure  pay when scheme fails

[59400 rows x 2 columns]

In [169]:
raw_df.loc[raw_df['water_quality'] == 'fluoride abandoned'] 
#raw_df['quality_group'].value_counts()

,id,status_group,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
6793,10874,non functional,0.0,2013-03-19,0,-30,0,39.363450,-6.894742e+00,Kwa Mbonde,...,never pay,fluoride abandoned,fluoride,insufficient,insufficient,machine dbh,borehole,groundwater,hand pump,hand pump
7372,46756,non functional,0.0,2012-11-10,World Vision,0,World vision,33.931583,-3.486847e+00,Kwa Kazengele,...,other,fluoride abandoned,fluoride,enough,enough,machine dbh,borehole,groundwater,other,other
10759,33573,non functional,0.0,2011-03-16,Government Of Tanzania,299,DWE,36.137635,-8.942505e+00,Sokoni,...,monthly,fluoride abandoned,fluoride,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
14432,33126,functional,0.0,2012-11-12,Netherlands,0,DWE,34.020473,-3.582536e+00,Busulwandulu,...,never pay,fluoride abandoned,fluoride,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
14595,31756,non functional,0.0,2012-10-22,Wsdp,0,AQUARMAN DRILLERS,34.107893,-3.417657e+00,None,...,never pay,fluoride abandoned,fluoride,enough,enough,machine dbh,borehole,groundwater,other,other
15872,20993,non functional,0.0,2011-03-05,Amref,18,AMREF,39.057837,-7.396576e+00,Kwa Mangwenya,...,never pay,fluoride abandoned,fluoride,dry,dry,shallow well,shallow well,groundwater,hand pump,hand pump
18015,60886,functional,0.0,2013-03-07,World Vision,952,World Vision,35.735400,-3.877415e+00,Kazaroho,...,never pay,fluoride abandoned,fluoride,enough,enough,hand dtw,borehole,groundwater,hand pump,hand pump
20732,58888,non functional,0.0,2013-02-17,Lamp,1524,DWE,35.594111,-4.340430e+00,Kwa Mathias,...,never pay,fluoride abandoned,fluoride,enough,enough,shallow well,shallow well,groundwater,other,other
22165,70990,functional,0.0,2013-02-10,Dwsp,0,DWE,0.000000,-2.000000e-08,Kwamagu,...,unknown,fluoride abandoned,fluoride,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
29148,46721,functional,0.0,2011-03-17,Government Of Tanzania,293,DWE,36.135270,-8.942596e+00,Msikitini,...,never pay,fluoride abandoned,fluoride,insufficient,insufficient,shallow well,shallow well,groundwater,hand pump,hand pump
31730,32143,non functional,0.0,2012-10-19,Government Of Tanzania,0,Government,33.809141,-3.441827e+00,Pius Mwandu,...,other,fluoride abandoned,fluoride,dry,dry,shallow well,shallow well,groundwater,hand pump,hand pump
32950,40880,non functional,0.0,2011-03-05,Rished,-17,DWE,38.946685,-5.379934e+00,Kwa Mzee Juma,...,never pay,fluoride abandoned,fluoride,insufficient,insufficient,shallow well,shallow well,groundwater,other,other
33201,38144,non functional,0.0,2013-01-29,Government Of Tanzania,1437,DWE,30.713918,-3.603296e+00,Kuzera Primary School,...,unknown,fluoride abandoned,fluoride,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
33395,54363,functional,0.0,2013-02-05,Wvt,0,WVT,0.000000,-2.000000e-08,Njia Panda,...,never pay,fluoride abandoned,fluoride,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
34135,22207,functional,0.0,2012-11-12,World Vision,0,World vision,34.021197,-3.583229e+00,Msituni,...,other,fluoride abandoned,fluoride,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
38992,60616,non functional,0.0,2013-03-19,0,-19,0,39.430507,-6.940968e+00,Shuleni,...,never pay,fluoride abandoned,fluoride,enough,enough,machine dbh,borehole,groundwater,hand pump,hand pump
50513,14139,non functional,0.0,2012-10-21,Rwssp,0,DWE,32.390626,-4.031776e+00,Kangeme,...,unknown,fluoride abandoned,fluoride,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump

Duplicate/ Similar Columns: 
* The ('extraction_type', 'extraction_type_group','extraction_type_class') are larger subgroupings/ generalizations of the data  
* The ('payment_type & 'payment') columns are completely duplicated I am going to drop payment_type 
* The ('water_quality' & 'quality_group') are very similar:  good correlates to "soft" / salty

# Data Cleaning

## Dropping Columns

In [153]:
df1 = df.drop(['water_quality', 'payment_type'], axis=1)

replace 0 in funder and installer to be unknown

In [141]:
#df.loc[(df['funder'] == '0') & (df['installer'] == '0')]  

#777 of the rows with no funder also have no installer  listed as well

Index(['id', 'status_group', 'amount_tsh', 'date_recorded', 'funder',
       'gps_height', 'installer', 'longitude', 'latitude', 'wpt_name',
       'num_private', 'basin', 'subvillage', 'region', 'region_code',
       'district_code', 'lga', 'ward', 'population', 'public_meeting',
       'recorded_by', 'scheme_management', 'scheme_name', 'permit',
       'construction_year', 'extraction_type', 'extraction_type_group',
       'extraction_type_class', 'management', 'management_group', 'payment',
       'payment_type', 'water_quality', 'quality_group', 'quantity',
       'quantity_group', 'source', 'source_type', 'source_class',
       'waterpoint_type', 'waterpoint_type_group'],
      dtype='object')

## EDA

In [6]:
#divide data by status_group
functional = df.loc[df['status_group'] == 'functional'] 
non_functional = df.loc[df['status_group'] == 'non functional'] 
functional_needs_repair = df.loc[df['status_group'] == 'functional needs repair']

In [52]:
m = folium.Map(location=[6.3690, 34.8888]) 
m

### Question: What is similar about functioning pumps which are producing enough good water?

In [39]:
good_enough_functional = functional.loc[(functional['quantity'] == 'enough') & (functional['quality_group'] == 'good')] 
good_enough_functional.head()

,id,status_group,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,69572,functional,6000.0,2011-03-14,Roman,1390,Roman,34.938093,-9.856322,none,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
2,34310,functional,25.0,2013-02-25,Lottery Club,686,World vision,37.460664,-3.821329,Kwa Mahundi,...,per bucket,soft,good,enough,enough,dam,dam,surface,communal standpipe multiple,communal standpipe
9,46144,functional,0.0,2011-08-03,Isingiro Ho,0,Artisan,30.626991,-1.257051,Kwapeto,...,never pay,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
12,36957,functional,0.0,2012-10-14,World Vision,0,World vision,33.798106,-3.290194,Pamba,...,other,soft,good,enough,enough,shallow well,shallow well,groundwater,hand pump,hand pump
13,50495,functional,0.0,2013-03-15,Lawatefuka Water Supply,1368,Lawatefuka water sup,37.092574,-3.181783,Kwa John Izack Mmari,...,monthly,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe

In [65]:
explore_df(df=good_enough_functional)

(19640, 41)
id                          0
status_group                0
amount_tsh                  0
date_recorded               0
funder                    739
gps_height                  0
installer                 743
longitude                   0
latitude                    0
wpt_name                    0
num_private                 0
basin                       0
subvillage                 42
region                      0
region_code                 0
district_code               0
lga                         0
ward                        0
population                  0
public_meeting            923
recorded_by                 0
scheme_management         678
scheme_name              7403
permit                    699
construction_year           0
extraction_type             0
extraction_type_group       0
extraction_type_class       0
management                  0
management_group            0
payment                     0
payment_type                0
water_quality               0
quality_group               0
quantity                    0
quantity_group              0
source                      0
source_type                 0
source_class                0
waterpoint_type             0
waterpoint_type_group       0
dtype: int64
['id', 'status_group', 'amount_tsh', 'date_recorded', 'funder', 'gps_height', 'installer', 'longitude', 'latitude', 'wpt_name', 'num_private', 'basin', 'subvillage', 'region', 'region_code', 'district_code', 'lga', 'ward', 'population', 'public_meeting', 'recorded_by', 'scheme_management', 'scheme_name', 'permit', 'construction_year', 'extraction_type', 'extraction_type_group', 'extraction_type_class', 'management', 'management_group', 'payment', 'payment_type', 'water_quality', 'quality_group', 'quantity', 'quantity_group', 'source', 'source_type', 'source_class', 'waterpoint_type', 'waterpoint_type_group']
<class 'pandas.core.frame.DataFrame'>
Int64Index: 19640 entries, 0 to 59396
Data columns (total 41 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     19640 non-null  int64
 1   status_group           19640 non-null  object
 2   amount_tsh             19640 non-null  float64
 3   date_recorded          19640 non-null  object
 4   funder                 18901 non-null  object
 5   gps_height             19640 non-null  int64
 6   installer              18897 non-null  object
 7   longitude              19640 non-null  float64
 8   latitude               19640 non-null  float64
 9   wpt_name               19640 non-null  object
 10  num_private            19640 non-null  int64
 11  basin                  19640 non-null  object
 12  subvillage             19598 non-null  object
 13  region                 19640 non-null  object
 14  region_code            19640 non-null  int64
 15  district_code          19640 non-null  int64
 16  lga                    19640 non-null  object
 17  ward                   19640 non-null  object
 18  population             19640 non-null  int64
 19  public_meeting         18717 non-null  object
 20  recorded_by            19640 non-null  object
 21  scheme_management      18962 non-null  object
 22  scheme_name            12237 non-null  object
 23  permit                 18941 non-null  object
 24  construction_year      19640 non-null  int64
 25  extraction_type        19640 non-null  object
 26  extraction_type_group  19640 non-null  object
 27  extraction_type_class  19640 non-null  object
 28  management             19640 non-null  object
 29  management_group       19640 non-null  object
 30  payment                19640 non-null  object
 31  payment_type           19640 non-null  object
 32  water_quality          19640 non-null  object
 33  quality_group          19640 non-null  object
 34  quantity               19640 non-null  object
 35  quantity_group         19640 non-null  object
 36  source                 19640 non-null  object
 37  source_type            19640 non-null  object
 38  source_class           19640 non-null  object
 39  waterpoint_type        19640 non-null  object
 40  waterpoint_type_group  19640 non-null  object
dtypes: float64(3), int64(7), object(31)
memory usage: 6.3+ MB
None
                 id     amount_tsh    gps_height     longitude      latitude  \
count  19640.000000   19640.000000  19640.000000  19640.000000  1.964000e+04
mean   37061.449236     573.787691    823.689257     34.333743 -6.016214e+00
std    21443.932338    4133.456708    749.829650      5.858232  2.945920e+00
min        1.000000       0.000000    -90.000000      0.000000 -1.156432e+01
25%    18498.000000       0.000000      0.000000     33.545232 -8.973389e+00
50%    36858.000000       0.000000    866.500000     34.943990 -6.109505e+00
75%    55595.250000     200.000000   1497.000000     37.077826 -3.327453e+00
max    74242.000000  250000.000000   2628.000000     40.320693 -2.000000e-08

        num_private   region_code  district_code    population  \
count  19640.000000  19640.000000   19640.000000  19640.000000
mean       0.434420     13.606263       4.988187    167.307841
std        5.708634     14.536203       8.426815    501.109928
min        0.000000      1.000000       1.000000      0.000000
25%        0.000000      5.000000       2.000000      0.000000
50%        0.000000     11.000000       3.000000     30.000000
75%        0.000000     17.000000       4.000000    168.000000
max      450.000000     99.000000      80.000000  11463.000000

       construction_year
count       19640.000000
mean         1404.701120
std           914.755798
min             0.000000
25%             0.000000
50%          1997.000000
75%          2007.000000
max          2013.000000

[36862    1
 51948    1
 8929     1
 45795    1
 6886     1
         ..
 54656    1
 60807    1
 5512     1
 7561     1
 34817    1
 Name: id, Length: 19640, dtype: int64,
 functional    19640
 Name: status_group, dtype: int64,
 0.0         10872
 500.0        1710
 50.0         1122
 1000.0        751
 20.0          526
             ...
 13000.0         1
 53.0            1
 590.0           1
 138000.0        1
 1300.0          1
 Name: amount_tsh, Length: 81, dtype: int64,
 2011-03-17    286
 2011-03-15    280
 2011-02-28    228
 2011-03-18    221
 2011-03-14    207
              ...
 2004-06-01      1
 2011-09-18      1
 2011-08-20      1
 2013-12-01      1
 2012-12-11      1
 Name: date_recorded, Length: 313, dtype: int64,
 Government Of Tanzania           2131
 Danida                           1277
 Private Individual                542
 Germany Republi                   538
 Unicef                            507
                                  ...
 Healt                               1
 Halmashaur                          1
 Egypt                               1
 Manyovu Agriculture Institute       1
 Caltas                              1
 Name: funder, Length: 854, dtype: int64,
  0       5572
 -20        26
 -5         23
  1264      22
 -19        21
          ...
  2155       1
  122        1
  138        1
  2187       1
  897        1
 Name: gps_height, Length: 2332, dtype: int64,
 DWE                   5964
 Commu                  569
 CES                    538
 DANID                  364
 Hesawa                 343
                       ...
 MASWI CO                 1
 PWD                      1
 KAGERA MINE              1
 Kando                    1
 Emmanuel kitaponda       1
 Name: installer, Length: 891, dtype: int64,
 0.000000     461
 39.103752      2
 37.318911      2
 37.534327      2
 37.314250      2
             ...
 33.449240      1
 34.558228      1
 34.053500      1
 32.711206      1
 37.205786      1
 Name: longitude, Length: 19164, dtype: int64,
 -2.000000e-08    461
 -6.990549e+00      2
 -6.983183e+00      2
 -6.989456e+00      2
 -7.177203e+00      2
                 ...
 -3.280978e+00      1
 -1.077660e+01      1
 -4.367134e+00      1
 -6.435060e+00      1
 -5.600758e+00      1
 Name: latitude, Length: 19164, dtype: int64,
 none                  2349
 Shuleni                383
 Zahanati               184
 Msikitini              160
 Kanisani                80
                       ...
 Kwa Silwamba             1
 Shelatoni                1
 Area Three Namba 2       1
 Ngayi                    1
 Kwa Mzee Mbondo          1
 Name: wpt_name, Length: 13425, dtype: int64,
 0      19303
 6         48
 8         31
 1         25
 45        25
 5         24
 15        24
 32        23
 93        21
 47        12
 3         11
 65        11
 17        10
 2          8
 7          6
 24         5
 11         5
 25         5
 58         4
 16         4
 10         4
 39         3
 9          3
 12         3
 41         3
 4          3
 26         2
 20         2
 22         2
 35         1
 450        1
 34         1
 131        1
 180        1
 27         1
 61         1
 80         1
 14         1
 38         1
 Name: num_private, dtype: int64,
 Rufiji                     3654
 Pangani                    3178
 Lake Victoria              2970
 Lake Nyasa                 2641
 Internal                   2002
 Wami / Ruvu                1916
 Lake Tanganyika            1750
 Ruvuma / Southern Coast     962
 Lake Rukwa                  567
 Name: basin, dtype: int64,
 Kati          151
 Majengo       140
 Shuleni       132
 Madukani      119
 M             110
              ...
 Kikonya         1
 Namyaya         1
 Mwamatale       1
 Kanywaveza      1
 Mtile           1
 Name: subvillage, Length: 8255, dtype: int64,
 Iringa           3818
 Kilimanjaro      1819
 Shinyanga        1444
 Mbeya            1331
 Kagera           1216
 Morogoro         1170
 Pwani            1165
 Ruvuma            963
 Arusha            915
 Kigoma            898
 Mwanza            732
 Tanga             731
 Manyara           627
 Dodoma            479
 Rukwa             419
 Mara              365
 Singida           364
 Tabora            348
 Dar es Salaam     322
 Mtwara            284
 Lindi             230
 Name: region, dtype: int64,
 11    3818
 3     1819
 17    1468
 12    1331
 18    1217
 5     1172
 10     963
 16     898
 6      841
 2      773
 4      729
 19     698
 21     627
 1      479
 15     419
 20     365
 13     364
 14     358
 60     324
 7      322
 80     228
 99     158
 24     142
 90      89
 9       37
 8        1
 Name: region_code, dtype: int64,
 1     4646
 4     4323
 2     3270
 3     2744
 5     1445
 7      980
 6      934
 30     453
 8      203
 53     148
 43     142
 23      95
 33      93
 13      61
 60      42
 62      42
 63      13
 67       5
 80       1
 Name: district_code, dtype: int64,
 Njombe         1873
 Bagamoyo        681
 Moshi Rural     580
 Hai             539
 Makete          534
                ...
 Kilindi           4
 Ukerewe           3
 Kiteto            3
 Moshi Urban       1
 Nachingwea        1
 Name: lga, Length: 122, dtype: int64,
 Igosi                  263
 Imalinyi               239
 Siha Kati              228
 Mdandu                 178
 Chalinze               153
                       ...
 Igigwa                   1
 Lusu                     1
 Milingoti Mashariki      1
 Karanga                  1
 Upuge                    1
 Name: ward, Length: 1578, dtype: int64,
 0       6613
 1       1999
 200      660
 150      652
 50       538
         ...
 5153       1
 723        1
 643        1
 1034       1
 1439       1
 Name: population, Length: 642, dtype: int64,
 True     17494
 False     1223
 Name: public_meeting, dtype: int64,
 GeoData Consultants Ltd    19640
 Name: recorded_by, dtype: int64,
 VWC                 11584
 WUG                  1819
 Water Board          1703
 WUA                  1554
 Water authority       952
 Private operator      447
 Parastatal            353
 Company               337
 Other                 174
 Trust                  25
 SWC                    14
 Name: scheme_management, dtype: int64,
 Chalinze wate                            348
 K                                        237
 None                                     197
 Kirua kahe gravity water supply trust    174
 Uroki-Bomang'ombe water sup              174
                                         ...
 BL Bingati B                               1
 jongoj                                     1
 Karongo water sup                          1
 Nyamisuli Water project                    1
 mwamagembe windmill piped scheme           1
 Name: scheme_name, Length: 1408, dtype: int64,
 True     13522
 False     5419
 Name: permit, dtype: int64,
 0       5848
 2008    1328
 2010    1273
 2009    1173
 2000     737
 2007     682
 2006     631
 2011     575
 2003     566
 1999     561
 2004     493
 2002     416
 1995     415
 2012     362
 1998     349
 2005     338
 1978     298
 1985     266
 1992     259
 1984     240
 2001     240
 1996     233
 1994     209
 1993     189
 1990     189
 1974     162
 1988     148
 1986     140
 1982     133
 1997     132
 1989     117
 1980     109
 1983     102
 1987      95
 1972      92
 1991      81
 1975      70
 2013      66
 1976      49
 1981      47
 1977      38
 1970      36
 1971      34
 1973      24
 1967      19
 1963      17
 1979      16
 1968      16
 1969      14
 1960       4
 1962       3
 1964       3
 1966       2
 1965       1
 Name: construction_year, dtype: int64,
 gravity              10817
 nira/tanira           2867
 submersible           1498
 swn 80                1129
 india mark ii          708
 ksb                    623
 mono                   617
 afridev                572
 other                  439
 other - rope pump      179
 other - swn 81          77
 cemo                    37
 india mark iii          29
 windmill                22
 walimi                  17
 other - play pump        9
 Name: extraction_type, dtype: int64,
 gravity            10817
 nira/tanira         2867
 submersible         2121
 swn 80              1129
 india mark ii        708
 mono                 617
 afridev              572
 other                439
 rope pump            179
 other handpump       103
 other motorpump       37
 india mark iii        29
 wind-powered          22
 Name: extraction_type_group, dtype: int64,
 gravity         10817
 handpump         5408
 submersible      2121
 motorpump         654
 other             439
 rope pump         179
 wind-powered       22
 Name: extraction_type_class, dtype: int64,
 vwc                 12294
 wug                  2203
 water board          1785
 wua                  1329
 private operator      970
 parastatal            411
 water authority       232
 other                 230
 company                99
 unknown                46
 trust                  24
 other - school         17
 Name: management, dtype: int64,
 user-group    17611
 commercial     1325
 parastatal      411
 other           247
 unknown          46
 Name: management_group, dtype: int64,
 never pay                6432
 pay per bucket           3894
 pay monthly              3665
 pay annually             2117
 unknown                  1637
 pay when scheme fails    1506
 other                     389
 Name: payment, dtype: int64,
 never pay     6432
 per bucket    3894
 monthly       3665
 annually      2117
 unknown       1637
 on failure    1506
 other          389
 Name: payment_type, dtype: int64,
 soft    19640
 Name: water_quality, dtype: int64,
 good    19640
 Name: quality_group, dtype: int64,
 enough    19640
 Name: quantity, dtype: int64,
 enough    19640
 Name: quantity_group, dtype: int64,
 spring                  7807
 shallow well            4160
 river                   3784
 machine dbh             2942
 hand dtw                 401
 rainwater harvesting     217
 dam                      145
 lake                     129
 other                     46
 unknown                    9
 Name: source, dtype: int64,
 spring                  7807
 shallow well            4160
 river/lake              3913
 borehole                3343
 rainwater harvesting     217
 dam                      145
 other                     55
 Name: source_type, dtype: int64,
 groundwater    15310
 surface         4275
 unknown           55
 Name: source_class, dtype: int64,
 communal standpipe             11777
 hand pump                       5669
 communal standpipe multiple     1319
 improved spring                  436
 other                            415
 cattle trough                     23
 dam                                1
 Name: waterpoint_type, dtype: int64,
 communal standpipe    13096
 hand pump              5669
 improved spring         436
 other                   415
 cattle trough            23
 dam                       1
 Name: waterpoint_type_group, dtype: int64]

#### Are there any trends in the funder in this category?

In [67]:
funder_good_enough_functional = good_enough_functional.groupby('funder').count().reset_index()

In [70]:
funder_good_enough_functional_over_100 = funder_good_enough_functional.loc[funder_good_enough_functional['id'] > 100].sort_values('id', ascending=False)

In [73]:
fig = go.Figure(data=[go.Bar(x=funder_good_enough_functional_over_100['funder'], y=funder_good_enough_functional_over_100['id'])])
# Customize aspect
fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5, opacity=0.6)
fig.update_layout(title_text='Funders on Sufficently Functioning Water Pumps Producing Good Water')
fig.show()

#### What years were the pumps in this category made?

In [81]:
construction_year_good_enough_functional = good_enough_functional.groupby('construction_year').count().reset_index()

In [90]:
construction_year_good_enough_functional.sum()

construction_year        105310
id                        19640
status_group              19640
amount_tsh                19640
date_recorded             19640
funder                    18901
gps_height                19640
installer                 18897
longitude                 19640
latitude                  19640
wpt_name                  19640
num_private               19640
basin                     19640
subvillage                19598
region                    19640
region_code               19640
district_code             19640
lga                       19640
ward                      19640
population                19640
public_meeting            18717
recorded_by               19640
scheme_management         18962
scheme_name               12237
permit                    18941
extraction_type           19640
extraction_type_group     19640
extraction_type_class     19640
management                19640
management_group          19640
payment                   19640
payment_type              19640
water_quality             19640
quality_group             19640
quantity                  19640
quantity_group            19640
source                    19640
source_type               19640
source_class              19640
waterpoint_type           19640
waterpoint_type_group     19640
dtype: int64

In [93]:
x= [1960, 1970, 1980, 1990, 2000, 2010] 
y = [79, 804, 1397, 2617, 6604, 2276]
fig = go.Figure(data=[go.Bar(x=x, y=y, hovertext=['~0.1%', '~4%', '~7%', '~13%', '~34', '~12%'])])
# Customize aspect
fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5, opacity=0.6)
fig.update_layout(title_text='Decade of Construction on Sufficently Functioning Water Pumps Producing Good Water')
fig.show()

#### What is the breakdown of payment type in this category?

In [60]:
#group by payment method
payment_good_enough_functional = good_enough_functional.groupby('payment_type').count() 
#payment_good_enough_functional.reset_index(inplace=True)

In [63]:
payment_good_enough_functional

,payment_type,id,status_group,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,...,payment,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
0,annually,2117,2117,2117,2117,2095,2117,2091,2117,2117,...,2117,2117,2117,2117,2117,2117,2117,2117,2117,2117
1,monthly,3665,3665,3665,3665,3652,3665,3651,3665,3665,...,3665,3665,3665,3665,3665,3665,3665,3665,3665,3665
2,never pay,6432,6432,6432,6432,5946,6432,5953,6432,6432,...,6432,6432,6432,6432,6432,6432,6432,6432,6432,6432
3,on failure,1506,1506,1506,1506,1503,1506,1503,1506,1506,...,1506,1506,1506,1506,1506,1506,1506,1506,1506,1506
4,other,389,389,389,389,387,389,386,389,389,...,389,389,389,389,389,389,389,389,389,389
5,per bucket,3894,3894,3894,3894,3858,3894,3856,3894,3894,...,3894,3894,3894,3894,3894,3894,3894,3894,3894,3894
6,unknown,1637,1637,1637,1637,1460,1637,1457,1637,1637,...,1637,1637,1637,1637,1637,1637,1637,1637,1637,1637

In [64]:
fig = go.Figure(data=[go.Bar(x=payment_good_enough_functional['payment_type'], y=payment_good_enough_functional['id'],
            hovertext=['~11%', '~19%', '~33%', '~8%', '~2%', '~20%', '~8%'])])
# Customize aspect
fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5, opacity=0.6)
fig.update_layout(title_text='Payment Methods on Sufficently Functioning Water Pumps Producing Good Water')
fig.show()

### Question: What trends can be identified in pumps built by the Tanzanian Government?  
15% of all water pumps in this data set were funded for by the Tanzanian Governement

In [102]:
tg_pumps = df.loc[df['funder'] == 'Government Of Tanzania'] 
tg_pumps

,id,status_group,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
25,22308,functional needs repair,0.0,2013-02-25,Government Of Tanzania,1273,DWE,37.422751,-3.317536,Kwa Tukai,...,unknown,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
28,19685,non functional,0.0,2013-03-05,Government Of Tanzania,1443,District council,37.611126,-3.263526,Kwa Kibakaya,...,monthly,soft,good,insufficient,insufficient,spring,spring,groundwater,communal standpipe,communal standpipe
32,57238,functional needs repair,0.0,2013-03-19,Government Of Tanzania,1481,DWE,37.492334,-3.290627,Kwa Philip Lyimo,...,never pay,soft,good,insufficient,insufficient,river,river/lake,surface,other,other
39,25,non functional,0.0,2013-02-11,Government Of Tanzania,1348,DWE,30.613305,-3.894561,Mkuyuni,...,unknown,soft,good,seasonal,seasonal,shallow well,shallow well,groundwater,hand pump,hand pump
41,12796,functional,500.0,2011-03-12,Government Of Tanzania,2469,Commu,33.927902,-9.204649,none,...,on failure,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59367,73019,functional,2000.0,2011-03-09,Government Of Tanzania,1977,Commu,34.338899,-9.565553,none,...,annually,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe
59375,50998,functional,40000.0,2011-08-03,Government Of Tanzania,54,DWE,39.046942,-5.061494,Sekondari,...,monthly,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59377,43986,non functional,0.0,2012-10-23,Government Of Tanzania,0,Government,33.437012,-4.423594,Fpct,...,never pay,soft,good,insufficient,insufficient,dam,dam,surface,communal standpipe multiple,communal standpipe
59391,44885,non functional,0.0,2013-08-03,Government Of Tanzania,540,Government,38.044070,-4.272218,Kwa,...,never pay,soft,good,enough,enough,river,river/lake,surface,communal standpipe,communal standpipe
59392,40607,non functional,0.0,2011-04-15,Government Of Tanzania,0,Government,33.009440,-8.520888,Benard Charles,...,never pay,soft,good,enough,enough,spring,spring,groundwater,communal standpipe,communal standpipe

#### What percentage of government pumps are functioning?

In [118]:
tg_pumps.groupby('status_group').count()

,id,amount_tsh,date_recorded,funder,gps_height,installer,longitude,latitude,wpt_name,num_private,...,payment_type,water_quality,quality_group,quantity,quantity_group,source,source_type,source_class,waterpoint_type,waterpoint_type_group
status_group,,,,,,,,,,,,,,,,,,,,,
functional,3720,3720,3720,3720,3720,3717,3720,3720,3720,3720,...,3720,3720,3720,3720,3720,3720,3720,3720,3720,3720
functional needs repair,701,701,701,701,701,701,701,701,701,701,...,701,701,701,701,701,701,701,701,701,701
non functional,4663,4663,4663,4663,4663,4662,4663,4663,4663,4663,...,4663,4663,4663,4663,4663,4663,4663,4663,4663,4663

In [116]:
x = ['Functional', 'Functional Needs Repair', 'Non Functional']
y = [3720, 701, 4663]

# Use the hovertext kw argument for hover text
fig = go.Figure(data=[go.Bar(x=x, y=y,
            hovertext=['~41%', '~8%', '~51%'])])
# Customize aspect
fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5, opacity=0.6)
fig.update_layout(title_text='Government Build Water Pumps by Status')
fig.show()

#### Who installs the pumps the govement builds?

In [121]:
installer_tg_pumps = tg_pumps.groupby('installer').count().reset_index()

In [122]:
fig = go.Figure(data=[go.Bar(x=installer_tg_pumps['installer'], y=installer_tg_pumps['id'])])
# Customize aspect
fig.update_traces(marker_color='rgb(158,202,225)', marker_line_color='rgb(8,48,107)',
                  marker_line_width=1.5, opacity=0.6)
fig.update_layout(title_text='Installers of Government Water Pumps')
fig.show()

# Working Line

In [8]:
df['water_quality'].value_counts()

soft                  50818
salty                  4856
unknown                1876
milky                   804
coloured                490
salty abandoned         339
fluoride                200
fluoride abandoned       17
Name: water_quality, dtype: int64

In [20]:
soft = df.loc[df['water_quality'] == 'soft']